# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['unweaver',
 'unweaver.algorithms',
 'unweaver.build',
 'unweaver.databases.geopackage',
 'unweaver.fields',
 'unweaver.geo',
 'unweaver.graphs',
 'unweaver.graphs.digraphgpkg',
 'unweaver.graphs.digraphgpkg.edges',
 'unweaver.graphs.digraphgpkg.inner_adjlists',
 'unweaver.graphs.digraphgpkg.nodes',
 'unweaver.graphs.digraphgpkg.outer_adjlists',
 'unweaver.network_adapters',
 'unweaver.network_adapters.geopackagenetwork',
 'unweaver.parsers',
 'unweaver.server',
 'unweaver.server.views']

package_data = \
{'': ['*']}

install_requires = \
['Fiona>=1.8.20,<2.0.0',
 'click>=7.0,<8.0',
 'flask>=1.1,<2.0',
 'geomet>=0.3.0,<0.4.0',
 'markupsafe==2.0.1',
 'networkx>=2.6.3,<3.0.0',
 'osm-humanized-opening-hours>=0.6.2,<0.7.0',
 'pyproj>=3.2.1,<4.0.0',
 'shapely>=1.6,<2.0',
 'webargs>=6.1,<7.0']

entry_points = \
{'console_scripts': ['unweaver = unweaver:cli.unweaver']}

setup_kwargs = {
    'name': 'unweaver',
    'version': '0.1.0',
    'description': 'A flexible, easy to run routing engine.',
    'long_description': None,
    'author': 'Nick Bolten',
    'author_email': 'nbolten@gmail.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'entry_points': entry_points,
    'python_requires': '>=3.8,<4.0',
}


setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
