# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='unweaver',
    version='0.1.0',
    description='A flexible, easy to run routing engine.',
    python_requires='==3.*,>=3.6.0',
    author='Nick Bolten',
    author_email='nbolten@gmail.com',
    license='MIT',
    entry_points={"console_scripts": ["unweaver = unweaver:cli.unweaver"]},
    packages=[
        'unweaver', 'unweaver.fields', 'unweaver.geo',
        'unweaver.network_queries', 'unweaver.parsers', 'unweaver.server',
        'unweaver.server.views'
    ],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'click==7.*,>=7.0.0', 'entwiner', 'flask==1.*,>=1.0.0',
        'shapely==1.*,>=1.6.0', 'webargs==5.*,>=5.3.0'
    ],
    dependency_links=[
        'git+https://github.com/nbolten/entwiner.git@f0f32d0#egg=entwiner'
    ],
    extras_require={
        "dev": [
            "black==18.9b0", "pre-commit==1.*,>=1.14.0", "pytest==5.*,>=5.2.0"
        ]
    },
)
