# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['unweaver',
 'unweaver.algorithms',
 'unweaver.fields',
 'unweaver.geo',
 'unweaver.graphs',
 'unweaver.parsers',
 'unweaver.server',
 'unweaver.server.views']

package_data = \
{'': ['*']}

install_requires = \
['click>=7.0,<8.0',
 'entwiner @ git+https://github.com/nbolten/entwiner.git@97be898',
 'flask>=1.1,<2.0',
 'shapely>=1.6,<2.0',
 'webargs>=6.1,<7.0']

entry_points = \
{'console_scripts': ['unweaver = unweaver:cli.unweaver']}

setup_kwargs = {
    'name': 'unweaver',
    'version': '0.1.0',
    'description': 'A flexible, easy to run routing engine.',
    'long_description': None,
    'author': 'Nick Bolten',
    'author_email': 'nbolten@gmail.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'entry_points': entry_points,
    'python_requires': '>=3.6,<4.0',
}


setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
